const participants = [
  {
    first_name: "Andrea",
    last_name: "Ngan",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "andrea@creativeresco.org",
  },
  {
    first_name: "Anjanette",
    last_name: "Davenport Hatter",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "",
  },
  {
    first_name: "Brooke",
    last_name: "Staton",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "brooke@reflexdc.com",
  },
  {
    first_name: "Bryan",
    last_name: "Lee Jr",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "bryan@colloqate.org",
  },
  {
    first_name: "Cedric",
    last_name: "Douglas",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "cedricdouglasdesign@gmail.com",
  },
  {
    first_name: "Chris",
    last_name: "Rudd",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "crudd2@id.iit.edu",
  },
  {
    first_name: "Claudia",
    last_name: "Paraschiv",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "claudia@studiofuldesign.com",
  },
  {
    first_name: "Denise Shante",
    last_name: "Brown",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "design@deniseshantebrown.com",
  },
  {
    first_name: "Elle",
    last_name: "Ramel",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "elleramel@gmail.com",
  },
  {
    first_name: "Forest",
    last_name: "Gregg",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "fgregg@datamade.us",
  },
  {
    first_name: "Jenny",
    last_name: "Lin",
    designer_type: "UX",
    bio: "",
    interviewed: true,
    email: "jwj.lin@gmail.com",
  },
  {
    first_name: "Julia",
    last_name: "Kong",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "julia.kong@reflexdc.com",
  },
  {
    first_name: "Katanya",
    last_name: "Raby",
    designer_type: "Urban Planner",
    bio: "",
    interviewed: true,
    email: "urbandreamsofmine@gmail.com",
  },
  {
    first_name: "Katherine",
    last_name: "Darnstadt",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "katherine@latentdesign.net",
  },
  {
    first_name: "Keesha",
    last_name: "Gaskins",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "keesha.gaskins@gmail.com",
  },
  {
    first_name: "Kenneth",
    last_name: "Bailey",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "kdb@ds4si.org",
  },
  {
    first_name: "Lorin",
    last_name: "Jackson",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "extrartinaire@gmail.com",
  },
  {
    first_name: "N'Deye",
    last_name: "Diakhate",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "ndiakhate93@gmail.com",
  },
  {
    first_name: "Nour",
    last_name: "Afat",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "narafat@umich.edu",
  },
  {
    first_name: "Olivia",
    last_name: "Nava",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "olivia.nava@gobeegroup.com",
  },
  {
    first_name: "Sabiha",
    last_name: "Basrai",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "sabiha@designaction.org ",
  },
  {
    first_name: "Shanelle",
    last_name: "Matthews",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "helloshanelle@gmail.com",
  },
  {
    first_name: "Sloan",
    last_name: "Leo",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "therealsloanleo@gmail.com",
  },
  {
    first_name: "Stephanie",
    last_name: "Burrell",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "me@stephanieariburrell.com",
  },
  {
    first_name: "Taylor",
    last_name: "Holloway",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "",
  },
  {
    first_name: "Taylor",
    last_name: "Holloway",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "",
  },
  {
    first_name: "Tonika",
    last_name: "Johnson",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "tonika.johnson@gmail.com",
  },
  {
    first_name: "Victoria",
    last_name: "Barnnett",
    designer_type: "Graphic",
    bio: "",
    interviewed: true,
    email: "veegs42@gmail.com",
  },
  {
    first_name: "Fo",
    last_name: "Wilson",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "",
  },
  {
    first_name: "Michelle",
    last_name: "Washington",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "",
  },
  {
    first_name: "Gabe",
    last_name: "Moreno",
    designer_type: "Designer",
    bio: "",
    interviewed: true,
    email: "",
  },
];

export default participants;
